<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crnc.Oms.DataAccess\Crnc.Oms.DataAccess.csproj" />
    <ProjectReference Include="..\Crnc.Oms.Domain\Crnc.Oms.Domain.csproj" />
  </ItemGroup>

</Project>
