version: '3'
services:

# Security context
  security-db:
    image: "mongo:latest"
    restart: always
    ports:
      - "27020:27017" 
  security-api:
    build: src/Server/src/Crnc.Oms.Security/
    restart: always
    ports:
      - "64708:80"
    environment:
      - "ConnectionStrings:OmsSecurityDb:Server=mongodb://security-db"
    depends_on: 
      - security-db