version: '3'
services:

# Message broker
  message-broker:
    image: rabbitmq:3-management
    container_name: 'crnc-oms-message-broker'
    restart: always
    ports:
      - "15673:15672" 
      - "5673:5672"

# Security context
  security-db:
    image: "mongo:4.2.3"
    container_name: 'crnc-oms-security-db'
    restart: always
    ports:
      - "27021:27017" 
  security-api:
    build: src/Server/src/Crnc.Oms.Security/
    container_name: 'crnc-oms-security-api'
    restart: always
    ports:
      - "8090:80"
    environment:
      - "ConnectionStrings:OmsSecurityDb:Server=mongodb://security-db"
      - "Cache:IsUse=true"
    depends_on: 
      - security-db      

  # Sales context
  sales-db:
    image: "postgres:9.6.17"
    container_name: 'crnc-oms-sales-db'
    restart: always 
    ports:
      - 5433:5432
    environment: 
      - POSTGRES_PASSWORD=docker
  sales-api:
    build: src/Server/src/Crnc.Oms.Sales/
    container_name: 'crnc-oms-sales-api'
    restart: always
    ports:
      - "8091:80"
    environment:
      - "ConnectionStrings:OmsSalesDb=Host=sales-db;Database=crnc_oms_sales_db;Username=postgres;Password=docker"          
      - "IntegrationEndpoints:NotificationServiceEndpoint=http://notification-gateway-api"      
      - "IntegrationEndpoints:SecurityServiceEndpoint=http://security-api"
      - "IntegrationEndpoints:MessageBrokerEndpoint=rabbitmq://message-broker"
    depends_on: 
      - sales-db
      - security-api
      - notification-gateway-api
      - message-broker

  # Notification context
  notification-email-api:
    build: src/Server/src/Crnc.Oms.Notification/Crnc.Oms.Notification.Email/
    container_name: 'crnc-oms-notification-email-api'
    restart: always
    ports:
      - "8104:80"
    environment:
      - "IntegrationEndpoints:MessageBrokerEndpoint=rabbitmq://message-broker"

  notification-push-api:
    build: src/Server/src/Crnc.Oms.Notification/Crnc.Oms.Notification.Push/
    container_name: 'crnc-oms-notification-push-api'
    restart: always
    environment:
      - "IntegrationEndpoints:UiEndpoint=http://localhost:8092"
      - "IntegrationEndpoints:MessageBrokerEndpoint=rabbitmq://message-broker"
    ports:
      - "8107:80"
  
  notification-gateway-api:
    build: src/Server/src/Crnc.Oms.Notification/Crnc.Oms.Notification.Gateway/
    container_name: 'crnc-oms-notification-gateway-api'
    restart: always
    ports:
      - "8100:80"
    environment:
      - "IntegrationEndpoints:EmailNotificationServiceEndpoint=http://notification-email-api"
      - "IntegrationEndpoints:PushNotificationServiceEndpoint=http://notification-push-api"
      - "IntegrationEndpoints:SecurityServiceEndpoint=http://security-api"
      - "IntegrationEndpoints:MessageBrokerEndpoint=rabbitmq://message-broker"
    depends_on: 
      - notification-email-api
      - notification-push-api
      - message-broker

  notification-push-client:
    build: src/Server/src/Crnc.Oms.Notification/Crnc.Oms.Notification.Push.Client/
    container_name: 'crnc-oms-notification-push-client'
    restart: always
    environment:
      - "IntegrationEndpoints:SecurityServiceEndpoint=http://security-api"
      - "IntegrationEndpoints:PushNotificationServiceEndpoint=http://notification-push-api"      
    depends_on:      
      - notification-push-api
      - security-api
      - message-broker

  prometheus:
    build: prometheus/
    restart: always
    ports:
      - "9090:9090"

  grafana:
    build: './grafana'
    container_name: 'crnc-oms-grafana'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=p@ssw0rd
    ports:
      - '3000:3000'
    
  # UI
  #crnc-oms-ui:
  #  build:
  #    context: "src/Client/"
  #    args:
  #      SECURITY_API_URL: "http://localhost:8090/api"
  #      SALES_API_URL: "http://localhost:8091/api"
  #      PUSH_HUBS_URL: "http://localhost:8107/api"
  #  restart: always
  #  ports:
  #    - "8092:80"      
  #  depends_on: 
  #    - security-api
  #    - sales-api       
  #    - notification-gateway-api
