<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="MassTransit" Version="6.2.1" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Crnc.Oms.Production.Domain\Crnc.Oms.Production.Domain.csproj" />
      <ProjectReference Include="..\Crnc.Oms.Production.Messaging.Contract\Crnc.Oms.Production.Messaging.Contract.csproj" />
    </ItemGroup>

</Project>
