<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Crnc.Oms.Sales.Domain\Crnc.Oms.Sales.Domain.csproj" />
      <ProjectReference Include="..\Crnc.Oms.Sales.Dto\Crnc.Oms.Sales.Dto.csproj" />
    </ItemGroup>

</Project>
