version: '3'
services:
  db:
    image: "postgres:latest"
    restart: always 
    ports:
      - 5432:5432
  web:
    build: .
    restart: always
    ports:
      - "64709:80"
    environment:
      - "ConnectionStrings:OmsSalesDb=Host=db;Database=crnc_oms_sales_db;Username=postgres;Password=docker"
    links:
      - db 
    depends_on: 
      - db