<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Crnc.Oms.Production.Domain\Crnc.Oms.Production.Domain.csproj" />
      <ProjectReference Include="..\Crnc.Oms.Production.DataAccess\Crnc.Oms.Production.DataAccess.csproj" />
    </ItemGroup>

</Project>
