<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit" Version="8.5.10" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Crnc.Oms.Notification.Gateway.Messaging.Contract\Crnc.Oms.Notification.Gateway.Messaging.Contract.csproj" />
    </ItemGroup>

</Project>
