<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Controllers" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Crnc.Oms.Sales.Application\Crnc.Oms.Sales.Application.csproj" />
      <ProjectReference Include="..\Crnc.Oms.Sales.Dto\Crnc.Oms.Sales.Dto.csproj" />
    </ItemGroup>

</Project>
