<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <RootNamespace>Crnc.Oms.Notification.Gateway.WebApi</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Crnc.Oms.Notification.Gateway.Application\Crnc.Oms.Notification.Gateway.Application.csproj" />
      <ProjectReference Include="..\Crnc.Oms.Notification.Gateway.Integration\Crnc.Oms.Notification.Gateway.Integration.csproj" />
      <ProjectReference Include="..\Crnc.Oms.Notification.Gateway.Messaging.Contract\Crnc.Oms.Notification.Gateway.Messaging.Contract.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
      <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
      <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    </ItemGroup>

</Project>
